apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  labels:
    apps: hello-world    
spec:
  template:
    spec:
      schedulerName: my-scheduler
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          name: hello-world
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "this is working"
      
