apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cfgmap
  namespace: kube-system
data:
  my-config.json: |
    {
      "TopoName": "./pi_nodes.csv",
      "RequestFile": "./prediction.csv",
      "SchedulerName": "my-scheduler",
      "LatencyPara": 0.000003336,
      "MemCap": 1000,
      "NodeNum": 10,
      "Beta": 0.5,
      "SlotNum": 30,
      "ReduFactor": 10000
    }
