---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hg-scheduler
  name: hg-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: hg-scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: hg-scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccount: default
      containers:
        - name: hg-scheduler
          image: cocc/histogram:v1.2
          volumeMounts:
          - name: config-volume
            mountPath: /app/config/my-config.json
            subPath: my-config.json
      volumes: 
      - name: config-volume
        configMap:
          name: my-cfgmap
