# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('mygraph', ['core'])
    module.source = [
    
        'model/sfc_tag.cc',
        'model/seq-ts-size-header.cc',
        'model/type.cc',
        'model/traffic_gen_application.cc',
        'helper/traffic_gen_helper.cc',
        'model/serverlessServer.cc',
        'helper/serverlessServer-helper.cc',
        'model/myAlgorithm.cc',
        'model/type.cc',
        'model/zipf.cc',
        'model/operation.cc',
        'model/network_controller.cc',
        'model/sfc_sink.cc',
        'helper/sfc_sink_helper.cc',
        'model/fixedcaching.cc',
        'model/hist.cc',
        'model/lru.cc',
        ]

    module_test = bld.create_ns3_module_test_library('mygraph')
    module_test.source = [
        'test/mygraph-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/mygraph-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'mygraph'
    headers.source = [
        'model/sfc_tag.h',
        'model/seq-ts-size-header.h',
        'model/type.h',
        'model/traffic_gen_application.h',
        'helper/traffic_gen_helper.h',
        'model/serverlessServer.h',
        'helper/serverlessServer-helper.h',
        'model/myAlgorithm.h',
        'model/type.h',
        'model/zipf.h',
        'model/operation.h',
        'model/network_controller.h',
        'model/sfc_sink.h',
        'helper/sfc_sink_helper.h',
        'model/fixedcaching.h',
        'model/hist.h',
        'model/lru.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

